### ISSUE TITLE
Using dnhsoft/shopware:4.0.1 Gives PDOException

### ISSUE THREAD

**Issue by dciccale** [dnhsoft/sw-docker-demo#2]
When running the following docker-compose.yml file

```yml
shop:
  image: dnhsoft/shopware:4.0.1
  links:
   - db
   - mailhog
  ports:
   - "8000:80"

db:
  image: dnhsoft/mysql-utf8:5.7
  volumes:
   - ".database:/var/lib/mysql"

pma:
  image: dnhsoft/phpmyadmin:4.6.3
  links:
   - db
  ports:
   - "8001:80"

mailhog:
  image: mailhog/mailhog
  expose:
   - "1025"
   - "8025"
  ports:
   - "8025:8025"
```

`docker-compose up -d` and going to `http://127.0.0.1` I get this error:

```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'admin'@'172.17.0.4' (using password: YES)' in /shopware/engine/Library/Zend/Db/Adapter/Pdo/Abstract.php:129 Stack trace: #0 /shopware/engine/Library/Zend/Db/Adapter/Pdo/Abstract.php(129): PDO->__construct('mysql:dbname=sh...', 'admin', '123456', Array) #1 /shopware/engine/Library/Zend/Db/Adapter/Pdo/Mysql.php(109): Zend_Db_Adapter_Pdo_Abstract->_connect() #2 /shopware/engine/Library/Enlight/Components/Db/Adapter/Pdo/Mysql.php(92): Zend_Db_Adapter_Pdo_Mysql->_connect() #3 /shopware/engine/Library/Zend/Db/Adapter/Abstract.php(315): Enlight_Components_Db_Adapter_Pdo_Mysql->_connect() #4 /shopware/engine/Shopware/Bootstrap.php(155): Zend_Db_Adapter_Abstract->getConnection() #5 [internal function]: Shopware_Bootstrap->initDb() #6 /shopware/engine/Library/Enlight/Bootstrap.php(304): call_user_func(Array) #7 /shopware/engine/Library/Enlight/Bootstrap.php(258): Enlight_Bootstrap->loadResource('Db') #8 /shopware/engine/Shopw in /shopware/engine/Library/Enlight/Components/Db/Adapter/Pdo/Mysql.php on line 101
```

What could this possibly be? Thanks in advance for any help

**Comment by chudomir-delchev-dnh** [comment]
Sorry to hear you had this problem.

Here is a correct docker-compose.yml file for your case:

```yml
shop:
  image: dnhsoft/shopware:4.0.1
  links:
   - db
   - mailhog
  ports:
   - "8000:80"
  environment:
   SWDB_USER: "root"

db:
  image: dnhsoft/mysql-utf8:5.6
  volumes:
   - ".database:/var/lib/mysql"
  environment:
   MYSQL_ROOT_PASSWORD: 123456

pma:
  image: dnhsoft/phpmyadmin:4.6.3
  links:
   - db
  ports:
   - "8001:80"

mailhog:
  image: mailhog/mailhog
  expose:
   - "1025"
   - "8025"
  ports:
   - "8025:8025"
```
